modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId="nebs"
version="${file.jarVersion}"
displayName="Neko's Enchanted Books"
updateJSONURL="https://infernalstudios.org/api/mods/nekosenchantedbooks/forge"
credits="Nekomaster, CGessinger, Jonathing"
authors="Infernal Studios"
description='''A small mod that enables adding unique textures for Enchanted Books. See our CurseForge page for what mods are natively supported and how you can add your own support!'''

[[dependencies.nebs]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)" # GatherDataEvent was moved
    ordering="NONE"
    side="BOTH"

[[dependencies.nebs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.3)"
    ordering="NONE"
    side="BOTH"
