modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="nebs" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Neko's Enchanted Books" #mandatory
updateJSONURL="https://infernalstudios.org/api/mods/nekosenchantedbooks/forge"
credits="Nekomaster, CGessinger, Jonathing" #optional
authors="Infernal Studios"
description='''A small mod that enables adding unique textures for Enchanted Books. See our CurseForge page for what mods are natively supported and how you can add your own support!'''

[[dependencies.nebs]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32.0.72,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.nebs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
