name: Build and publish
on:
  push:
    tags:
      - '1.18/*'
    branches: [ '1.18' ]
    paths:
      - 'build.gradle'
      - 'build.properties'
  pull_request:
    branches: [ '1.18' ]
    paths:
      - 'src/**'
      - 'build.gradle'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
          
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle Build
        run: ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/
  
  publish:
    runs-on: ubuntu-20.04
    if: ${{ success() && github.ref_type == 'tag' }}
    needs: [ build ]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/

      - name: Publish build artifacts
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: VZWuyRVr
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 441114
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}