name: Build
on:
  push:
    paths:
      - '*/build.gradle'
      - '*/build.properties'
  pull_request:
    paths:
      - '*/src/**'
      - '*/build.gradle'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build

      - name: Move build artifacts to one directory
        run: |
          mkdir build
          mkdir build/libs
          mv */build/libs/*.jar build/libs -v

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/
